language: go
go:
  - 1.3
  - 1.4
  - release
  - tip

script:
  # pull all dependencies manually to see how many we have
  # remove them at all if possible
  - go get golang.org/x/tools/imports

  # run standard go tests
  - go test -v ./...
  - go test -race ./...

  # test me with myself
  - go run cmd/godog/main.go
