language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - release
  - tip

script:
  # linters and vet
  - (go version | grep "go1.1") || go get golang.org/x/tools/cmd/vet
  - (go version | grep "go1.1") || go get github.com/golang/lint/golint

  # pull all external dependencies
  - go get github.com/cucumber/gherkin-go
  - go get github.com/shiena/ansicolor

  # run standard go tests
  - go test -v ./...
  - go test -race ./...

  # run features
  - go run cmd/godog/main.go -f progress

  # code correctness
  - sh -c 'RES="$(go fmt ./...)"; if [ ! -z "$RES" ]; then echo $RES; exit 1; fi'
  - sh -c 'RES="$(golint ./...)"; if [ ! -z "$RES" ]; then echo $RES; exit 1; fi'
  - go vet ./...
