language: go
go:
  - 1.4
  - 1.5
  - 1.6
  - tip

script:
  # pull all external dependencies
  - go get gopkg.in/cucumber/gherkin-go.v3
  - go get github.com/shiena/ansicolor

  # run standard go tests
  - go vet ./...
  - go fmt ./...
  - go test -v
  - go test -race

  # run features
  - go run cmd/godog/main.go --format=progress --concurrency=4
