language: go
go:
  - 1.3
  - 1.4
  - release
  - tip

script:
  # pull all dependencies
  - go get -t ./...

  # run standard go tests
  - go test -v ./...
  - go test -race ./...

  # test me with myself
  - go run cmd/godog/main.go
