version: 2.1

executors:
  go1_11:
    docker:
      - image: circleci/golang:1.11
    environment:
      - GOROOT: "/usr/local/go"
      - GOPATH: "/go"
      - PATH: ${GOPATH}/bin:${GOROOT}/bin:${PATH}
  go1_12:
    docker:
    - image: circleci/golang:1.12
  go1_13:
    docker:
    - image: circleci/golang:1.13

commands:
  vet:
    description: "Run go vet"
    steps:
      - run: go vet github.com/cucumber/godog
      - run: go vet github.com/cucumber/godog/gherkin
      - run: go vet github.com/cucumber/godog/colors
  
  fmt:
    description: "Run go fmt"
    steps:
      - run: test -z "$(go fmt ./...)"

  godog:
    description: "Run godog"
    steps:
      - run: godog -f progress

  go_test:
    description: "Run go test"
    steps:
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic

  all:
    description: "Run all commands against godog code"
    steps:
      - vet
      - fmt
      - godog
      - go_test

jobs:
  go1_11:
    working_directory: /go/src/github.com/cucumber/godog
    executor: go1_11
    steps:
      - all

  go1_12:
    working_directory: /go/src/github.com/cucumber/godog
    executor: go1_12
    steps:
      - all

  go1_13:
    working_directory: /go/src/github.com/cucumber/godog
    executor: go1_13
    steps:
      - all
      

workflows:
  version: 2
  test:
    jobs:
      - go1_11
      # - go1_12
      # - go1_13
