version: 2.1

executors:
  go1_11:
    docker:
    - image: circleci/golang:1.11
  go1_12:
    docker:
    - image: circleci/golang:1.12
  go1_13:
    docker:
    - image: circleci/golang:1.13

jobs:
  go1_11:
    working_directory: /go/src/github.com/cucumber/godog
    executor: go1_11
    steps:
      - checkout
      - run: make test

  go1_12:
    working_directory: /go/src/github.com/cucumber/godog
    executor: go1_12
    steps:
      - checkout
      - run: make test

  go1_13:
    working_directory: /go/src/github.com/cucumber/godog
    executor: go1_13
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - go1_11
      - go1_12
      - go1_13
